//! ffmpeg + GPU gated integration test for the full-timeline export spine
//! (`export::run_export`).
//!
//! Builds a single short video clip on a one-track timeline, runs the whole
//! orchestrator (plan → composite every frame → encode), and asserts the output
//! `.mp4` exists and `ffprobe` reads back the expected width/height/codec and a
//! matching frame count.
//!
//! Auto-skips when ffmpeg/ffprobe are missing OR when no GPU adapter is
//! available (CI/headless), so the default `cargo test` stays green offline.
//! Nothing is downloaded — the fixture media is generated by ffmpeg's lavfi.

use std::path::Path;
use std::process::Command;

use opentake_domain::{
    Clip, ClipType, MediaManifest, MediaManifestEntry, MediaSource, Timeline, Track,
};

/// True when both ffmpeg and ffprobe are on PATH.
fn ffmpeg_ready() -> bool {
    Command::new("ffmpeg")
        .arg("-version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
        && Command::new("ffprobe")
            .arg("-version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
}

/// Generate an N-frame test video at `path`. Returns false (→ skip) on failure.
fn make_video(path: &Path, w: u32, h: u32, fps: u32, frames: u32) -> bool {
    let dur = frames as f64 / fps as f64;
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            &format!("testsrc=duration={dur}:size={w}x{h}:rate={fps}"),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// ffprobe a single stream field as a trimmed string.
fn probe_field(path: &Path, entry: &str) -> Option<String> {
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            entry,
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(path)
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    Some(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

/// Count decoded video frames via ffprobe.
fn probe_frame_count(path: &Path) -> Option<u64> {
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-count_frames",
            "-show_entries",
            "stream=nb_read_frames",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(path)
        .output()
        .ok()?;
    String::from_utf8_lossy(&out.stdout).trim().parse().ok()
}

/// Build a 1080p timeline with one short video clip referencing `asset-1`.
fn build_timeline(frames: i32, src_w: i32, src_h: i32, src_fps: f64) -> Timeline {
    let mut tl = Timeline::new(); // 30fps / 1920x1080 by default
    tl.fps = src_fps.round() as i32;
    let mut track = Track::new("t1", ClipType::Video);
    let clip = Clip::new("clip-1", "asset-1", 0, frames);
    track.clips.push(clip);
    tl.tracks.push(track);
    // src dims are carried via the manifest entry, not the timeline.
    let _ = (src_w, src_h);
    tl
}

/// Build a manifest with one external video asset pointing at `media_path`.
fn build_manifest(media_path: &Path, src_w: i32, src_h: i32, src_fps: f64) -> MediaManifest {
    let mut manifest = MediaManifest::new();
    manifest.entries.push(MediaManifestEntry {
        id: "asset-1".into(),
        name: "test.mp4".into(),
        kind: ClipType::Video,
        source: MediaSource::External {
            absolute_path: media_path.to_string_lossy().into_owned(),
        },
        duration: 1.0,
        generation_input: None,
        source_width: Some(src_w),
        source_height: Some(src_h),
        source_fps: Some(src_fps),
        has_audio: Some(false),
        folder_id: None,
        cached_remote_url: None,
        cached_remote_url_expires_at: None,
    });
    manifest
}

// The orchestrator under test lives in the lib crate's `export` module
// (`pub mod export` / `pub fn run_export`). Integration tests compile against the
// `rlib` target, so we drive it directly. `opentake_tauri_lib` is the lib name
// (see `[lib] name` in src-tauri/Cargo.toml).
use opentake_tauri_lib::export::{run_export, ExportQuality, ExportRequest};

#[test]
fn export_full_timeline_produces_playable_mp4() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg/ffprobe not available");
        return;
    }

    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("src.mp4");
    let out = dir.path().join("out.mp4");

    // Source: 320x240 @ 10fps, 6 frames (0.6s). Small + fast.
    let (sw, sh, sfps, frames) = (320, 240, 10, 6);
    if !make_video(&src, sw, sh, sfps, frames) {
        eprintln!("skip: could not generate fixture media");
        return;
    }

    let timeline = build_timeline(frames as i32, sw as i32, sh as i32, sfps as f64);
    let manifest = build_manifest(&src, sw as i32, sh as i32, sfps as f64);

    let req = ExportRequest {
        out_path: out.to_string_lossy().into_owned(),
        codec: Default::default(), // H.264
        quality: ExportQuality::P720,
    };

    let summary = match run_export(&timeline, &manifest, &None, &req) {
        Ok(s) => s,
        Err(e) => {
            // The most common offline cause is no GPU adapter; treat that as a
            // skip rather than a hard failure (matches the ffmpeg auto-skip).
            if e.contains("no GPU device") {
                eprintln!("skip: no GPU adapter available ({e})");
                return;
            }
            panic!("export failed: {e}");
        }
    };

    // 1080p export of a 320x240 (4:3) source: short side 240 → 720 → scale 3.0,
    // so 960x720 (export_render_size scales the canvas, not the source). The
    // canvas is the timeline's 1920x1080 though, so short side 1080 → 720 →
    // 1280x720. Assert against what the orchestrator reported and what ffprobe
    // reads back — they must agree.
    assert!(out.exists(), "output file should exist");
    assert_eq!(summary.frame_count, frames as i32);
    assert_eq!(summary.fps, sfps as i32);

    let pw: u32 = probe_field(&out, "stream=width").unwrap().parse().unwrap();
    let ph: u32 = probe_field(&out, "stream=height").unwrap().parse().unwrap();
    assert_eq!(pw, summary.width, "probed width matches reported");
    assert_eq!(ph, summary.height, "probed height matches reported");
    assert!(
        pw.is_multiple_of(2) && ph.is_multiple_of(2),
        "encoded dims are even"
    );

    let codec = probe_field(&out, "stream=codec_name").unwrap();
    assert_eq!(codec, "h264", "codec should be H.264");

    let nframes = probe_frame_count(&out).unwrap();
    assert_eq!(
        nframes, frames as u64,
        "encoded frame count matches timeline"
    );
}
