//! ffmpeg-backed integration tests for the decode/probe/pcm/thumbnail/waveform
//! and encode round-trip paths.
//!
//! These verify the chosen `ffmpeg-sidecar` (CLI) backend works end-to-end with
//! the locally installed ffmpeg (8.1 here). They **auto-skip** when ffmpeg /
//! ffprobe are not on `PATH`, so the default `cargo test` stays green and offline
//! on machines without ffmpeg — the test fixtures are generated by ffmpeg itself
//! (lavfi sources), so nothing is downloaded.

use std::path::Path;
use std::process::Command;

use opentake_media::ffmpeg_status::{ffmpeg_available, ffprobe_available};
use opentake_media::{
    decode_frame_at, encode, extract_pcm, probe, video_thumbnails, waveform, ExportPreset,
    ExportResolution, FrameRequest, PcmFormat, PcmSpec, VideoCodec, VideoEncoder,
};

/// Generate a 2 s 320x240@10fps test video with a 440 Hz sine audio track.
fn make_av(path: &Path) -> bool {
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=2:size=320x240:rate=10",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=2",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-shortest",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Generate a 1 s silent-but-present sine audio-only file.
fn make_audio(path: &Path) -> bool {
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=220:duration=1",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

#[test]
fn probe_reports_dimensions_fps_and_audio() {
    if !ffprobe_available() {
        eprintln!("skip: ffprobe not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        eprintln!("skip: could not generate test media");
        return;
    }

    let p = probe(&av).unwrap();
    assert!(p.has_video);
    assert!(p.has_audio);
    assert_eq!(p.width, Some(320));
    assert_eq!(p.height, Some(240));
    assert!(p.fps.unwrap() > 9.0 && p.fps.unwrap() < 11.0);
    assert!(p.duration_secs > 1.5 && p.duration_secs < 2.5);
}

#[test]
fn decode_frame_returns_rgba_of_expected_size() {
    if !ffmpeg_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }

    let req = FrameRequest {
        time_secs: 1.0,
        max_size: (0, 0),
        tolerance_secs: 1.0,
        apply_rotation: true,
    };
    let (_actual, frame) = decode_frame_at(&av, &req).unwrap();
    assert_eq!(frame.width, 320);
    assert_eq!(frame.height, 240);
    assert_eq!(frame.rgba.len(), 320 * 240 * 4);
}

#[test]
fn decode_frame_scales_within_box() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let req = FrameRequest {
        time_secs: 0.5,
        max_size: (120, 68),
        tolerance_secs: 1.0,
        apply_rotation: true,
    };
    let (_t, frame) = decode_frame_at(&av, &req).unwrap();
    // 320x240 into 120x68 → height-limited (68), width 90.
    assert!(frame.width <= 120 && frame.height <= 68);
    assert_eq!(
        frame.rgba.len(),
        frame.width as usize * frame.height as usize * 4
    );
}

#[test]
fn extract_pcm_yields_16k_mono() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    let pcm = extract_pcm(&av, &spec, None).unwrap();
    // ~2 s of 16 kHz mono ≈ 32000 samples (allow generous tolerance).
    assert!(pcm.samples_f32.len() > 24_000 && pcm.samples_f32.len() < 40_000);
    assert!((pcm.duration_secs() - 2.0).abs() < 0.5);
}

#[test]
fn extract_pcm_range_is_shorter() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    // 0.5 s window ≈ 8000 samples.
    let pcm = extract_pcm(&av, &spec, Some((0.5, 1.0))).unwrap();
    let n = pcm.samples_f32.len();
    assert!(n > 4_000 && n < 12_000, "got {n} samples for a 0.5s window");
}

#[test]
fn extract_pcm_no_audio_track_errors() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let video_only = dir.path().join("v.mp4");
    let ok = Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=1:size=64x64:rate=5",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-y",
        ])
        .arg(&video_only)
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if !ok {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    let err = extract_pcm(&video_only, &spec, None);
    assert!(
        err.is_err(),
        "expected NoTrack error for video without audio"
    );
}

#[test]
fn waveform_has_expected_bucket_count() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let audio = dir.path().join("a.wav");
    if !make_audio(&audio) {
        return;
    }
    // 1 s → max(4000, 150) = 4000 buckets, values in [0,1].
    let wf = waveform(&audio, 1.0).unwrap();
    assert_eq!(wf.len(), 4000);
    assert!(wf.iter().all(|&v| (0.0..=1.0).contains(&v)));
    // A 220 Hz tone is loud → at least some buckets well below 1 (not silence).
    let min = wf.iter().copied().fold(f32::INFINITY, f32::min);
    assert!(min < 0.5, "expected loud buckets, min={min}");
}

#[test]
fn video_thumbnails_generates_and_caches() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let cache = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }

    // 2 s clip (<10) → interval 1 → times 0,1 → up to 2 thumbnails.
    let thumbs = video_thumbnails(cache.path(), &av, 2.0, None).unwrap();
    assert!(!thumbs.is_empty());
    assert!(thumbs.len() <= 2);
    // Tiles scaled within the 120x68 box.
    assert!(thumbs[0].image.width <= 120 && thumbs[0].image.height <= 68);

    // Second call hits the sprite cache and returns the same count.
    let again = video_thumbnails(cache.path(), &av, 2.0, None).unwrap();
    assert_eq!(again.len(), thumbs.len());
}

#[test]
fn encode_roundtrip_produces_playable_video() {
    if !ffmpeg_available() || !ffprobe_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("out.mp4");

    let preset = ExportPreset::new(VideoCodec::H264, ExportResolution::P720);
    let (w, h) = (64u32, 64u32);
    let mut enc = VideoEncoder::new(&out, w, h, 10, &preset).unwrap();
    // Push 10 frames of solid color.
    for i in 0..10u8 {
        let mut rgba = vec![0u8; (w * h * 4) as usize];
        for px in rgba.chunks_exact_mut(4) {
            px[0] = i * 20;
            px[1] = 100;
            px[2] = 200;
            px[3] = 255;
        }
        enc.push_frame(&opentake_media::RgbaFrame::new(w, h, rgba))
            .unwrap();
    }
    enc.finish().unwrap();

    // The output decodes back to a 64x64 video of ~1 s.
    let p = probe(&out).unwrap();
    assert!(p.has_video);
    assert_eq!(p.width, Some(64));
    assert_eq!(p.height, Some(64));
    assert!(p.duration_secs > 0.5);

    // Ensure the encode module's preset arg builder agrees with reality.
    let _ = encode::preset::even_dimension(63); // referenced for coverage
}
